In [1]:
import numpy as np
import torch

# 1. Basic Matrix Operations with NumPy and PyTorch

# 1.1  NumPy Arithmetic

In [2]:
A = np.array([[1,2], [3,4], [5,6]])
B = np.array([[-1,1], [1,-1], [-1,1]])

# A + B
print('1. A + B = \n', A + B, '\n')
# A o B
print('2. A o B = \n', A * B,'\n')
# ATB
print('3. ATB = \n', A.T @ B, '\n')
# ABT
print('4. ABT = \n', A @ B.T, '\n')
# AB
print('5. AB = impossible. This is because the shape of each matrix is not matched.')

1. A + B = 
 [[0 3]
 [4 3]
 [4 7]] 

2. A o B = 
 [[-1  2]
 [ 3 -4]
 [-5  6]] 

3. ATB = 
 [[-3  3]
 [-4  4]] 

4. ABT = 
 [[ 1 -1  1]
 [ 1 -1  1]
 [ 1 -1  1]] 

5. AB = impossible. This is because the shape of each matrix is not matched.


## 1.2 PyTorch Arithmetic

In [3]:
A_pt = torch.FloatTensor(A)
B_pt = torch.FloatTensor(B)
print(A_pt, '\n', B_pt, '\n')

# A + B
print('1. A + B = \n', A_pt + B_pt, '\n')
# A o B
print('2. A o B = \n', A_pt.mul(B_pt),'\n')
# ATB
print('3. ATB = \n', A_pt.T.matmul(B_pt), '\n')
# ABT
print('4. ABT = \n', A_pt.matmul(B_pt.T), '\n')
# AB
print('5. AB = impossible. This is because the shape of each matrix is not matched.')

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]]) 
 tensor([[-1.,  1.],
        [ 1., -1.],
        [-1.,  1.]]) 

1. A + B = 
 tensor([[0., 3.],
        [4., 3.],
        [4., 7.]]) 

2. A o B = 
 tensor([[-1.,  2.],
        [ 3., -4.],
        [-5.,  6.]]) 

3. ATB = 
 tensor([[-3.,  3.],
        [-4.,  4.]]) 

4. ABT = 
 tensor([[ 1., -1.,  1.],
        [ 1., -1.,  1.],
        [ 1., -1.,  1.]]) 

5. AB = impossible. This is because the shape of each matrix is not matched.
